# Generated by Django 5.2.7 on 2025-11-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_archivedpatient_hcstaff_rename_gender_patient_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedpatient',
            name='fingerprint_template',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='fingerprint_template',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
