# Generated by Django 5.2.8 on 2025-11-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_archivedpatient_hcstaff_rename_gender_patient_sex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivedvitalsigns',
            old_name='heart_rate',
            new_name='pulse_rate',
        ),
        migrations.RenameField(
            model_name='vitalsigns',
            old_name='heart_rate',
            new_name='pulse_rate',
        ),
    ]
