# Generated by Django 5.2.1 on 2025-11-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_archivedpatient_fingerprint_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('SERVING', 'Currently Being Served'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=10),
        ),
    ]
