# Generated by Django 5.2.7 on 2025-11-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_queueentry_served_at_queueentry_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivedpatient',
            old_name='middle_initial',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='middle_initial',
            new_name='middle_name',
        ),
    ]
