# Generated by Django 5.2.8 on 2025-11-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_archivedpatient_archive_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedvitalsigns',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='device_id',
        ),
    ]
