# Generated by Django 5.2.8 on 2025-11-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_archivedpatient_archive_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedpatient',
            name='archive_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivedpatient',
            name='archived_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hcstaff',
            name='username',
            field=models.CharField(default='staf', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivedvitalsigns',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
