# Generated by Django 5.2.8 on 2025-11-12 13:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_archivedvitalsigns_device_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivedpatient',
            old_name='pin',
            new_name='patient_pin',
        ),
        migrations.RenameField(
            model_name='archivedvitalsigns',
            old_name='heart_rate',
            new_name='pulse_rate',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pin',
            new_name='patient_pin',
        ),
        migrations.RenameField(
            model_name='vitalsigns',
            old_name='heart_rate',
            new_name='pulse_rate',
        ),
        migrations.RemoveField(
            model_name='archivedpatient',
            name='fingerprint_id',
        ),
        migrations.RemoveField(
            model_name='archivedvitalsigns',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='hcstaff',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fingerprint_id',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='bmi',
        ),
        migrations.AddField(
            model_name='archivedpatient',
            name='biometric_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='hcstaff',
            name='username',
            field=models.CharField(default='staff', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='biometric_id',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='archivedpatient',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='archivedqueueentry',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='api.archivedpatient'),
        ),
        migrations.AlterField(
            model_name='archivedvitalsigns',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='archivedvitalsigns',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='api.archivedpatient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='barangay',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='api.patient'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='priority_status',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('NORMAL', 'Normal')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='queue_number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('COMPLETED', 'Completed')], default='WAITING', max_length=9),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='api.patient'),
        ),
    ]
