# Generated by Django 5.2.8 on 2025-11-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_archivedpatient_archive_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedpatient',
            name='archive_reason',
        ),
        migrations.RemoveField(
            model_name='archivedpatient',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='archivedvitalsigns',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='device_id',
        ),
    ]
