# Generated by Django 5.2.8 on 2025-11-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_pin_archivedpatient_patient_pin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hcstaff',
            name='id',
        ),
        migrations.RemoveField(
            model_name='queueentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vitalsigns',
            name='id',
        ),
        migrations.AddField(
            model_name='hcstaff',
            name='staff_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='queue_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='vitals_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
