# Generated by Django 5.2.8 on 2025-11-12 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_hcstaff_id_remove_queueentry_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedpatient',
            name='archive_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivedpatient',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hcstaff'),
        ),
    ]
