# Generated by Django 5.2.7 on 2025-11-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_patient_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitalsigns',
            old_name='BMI',
            new_name='bmi',
        ),
    ]
