# Generated by Django 5.2.7 on 2025-11-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_bmi_vitalsigns_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsigns',
            name='blood_pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
