# Generated by Django 5.2.7 on 2025-11-02 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_patient_id_remove_patient_middle_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='patient',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='api.patient'),
        ),
    ]
