# Generated by Django 5.2.7 on 2025-11-02 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_vitalsigns_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='api.patient'),
        ),
    ]
