# Generated by Django 5.2.7 on 2025-11-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_vitalsigns_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
