# Generated by Django 5.2.7 on 2025-11-02 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_patient_middle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedPatient',
            fields=[
                ('patient_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=6)),
                ('contact', models.CharField(max_length=11)),
                ('address', models.TextField(max_length=300)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('pin', models.CharField(max_length=255)),
                ('fingerprint_id', models.CharField(blank=True, max_length=4, null=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archive_reason', models.TextField(blank=True, null=True)),
                ('original_created_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hcstaff')),
            ],
            options={
                'verbose_name': 'Archived Patient',
                'db_table': 'archived_patient',
            },
        ),
        migrations.CreateModel(
            name='ArchivedQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=10)),
                ('entered_at', models.DateTimeField()),
                ('queue_number', models.CharField(max_length=10)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='api.archivedpatient')),
            ],
            options={
                'db_table': 'archived_queue_entry',
            },
        ),
        migrations.CreateModel(
            name='ArchivedVitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_time_recorded', models.DateTimeField()),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('oxygen_saturation', models.FloatField(blank=True, null=True)),
                ('blood_pressure', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='api.archivedpatient')),
            ],
            options={
                'db_table': 'archived_vital_signs',
            },
        ),
    ]
